apiVersion: v1
kind: ConfigMap
metadata:
  name: sfc-configmap
  namespace: solarflare
data:
  onload-version: 201804-rc0.6
  reg-exp-sfc: (?m)[\r\n]+^.*SFC[6-9].*$
  socket-name: sfcNIC
  resource-name: solarflare/smartNIC
  k8s-api: http://127.0.0.1:8080
  node-label-onload-version: device.sfc.onload-version

